# Generated by Django 4.1.13 on 2025-02-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.URLField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/image/')),
            ],
        ),
    ]
