# Generated by Django 4.1.13 on 2025-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='contact',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.URLField(default='https://example.com/default-location'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='static/image/Form_to_Home.jpeg', upload_to='static/image/'),
        ),
    ]
