# Generated by Django 4.1.13 on 2025-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='image/Form_to_Home.jpeg', upload_to='image/'),
        ),
    ]
