# Generated by Django 4.1.13 on 2025-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_order_city_order_postal_code_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
