# Generated by Django 4.1.13 on 2025-02-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_order_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default='deliver', max_length=10),
        ),
    ]
