# Generated by Django 4.1.13 on 2025-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_kg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
